version: '3.7'
services:
  mongodb:
    image: 'mongo'
    container_name: 'mongodb'
    network_mode: host
    ports: 
      - '27017:27017'
    # volumes:
    #   - './dockervolume/mongodb:/data/db'
    
  api:
    container_name: 'hospital-compose'
    build: .
    network_mode: host
    ports:
      - '8080:8080'
    volumes:
      - '/hospital'
    depends_on:
      - 'mongodb'
